loom.platform=fabric
minecraft_version=25w32a
fabric_loader_version=0.17.2
fabric_api_version=0.131.2+1.21.9
alinlib_minecraft_version=25w32a
minecraft_dependency=>1.21.8

modrinth_title = [1.21.9]
modrinth_versions=25w32a
#
modmenu_version=15.0.0-beta.3
replaymod=1.21.7-2.6.23
plasmovoice=fabric-1.21.6-2.1.5
svc=fabric-25w32a-2.5.36
waterplayer=wGp8PM6k
flashback=hQkBepoB