loom.platform=fabric
minecraft_version=1.21.9
fabric_loader_version=0.17.3
fabric_api_version=0.134.0+1.21.9
alinlib_minecraft_version=1.21.9
minecraft_dependency=>=1.21.9

modrinth_title = [1.21.9]
modrinth_versions=1.21.9, 1.21.10
#
modmenu_version=16.0.0-rc.1
replaymod=1.21.7-2.6.23
plasmovoice=fabric-1.21.6-2.1.5
svc=fabric-25w32a-2.5.36
waterplayer=wGp8PM6k
flashback=hQkBepoB